APA_KR/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from APA_KR import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

else:
    urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('feedback_shift_generator/', views.feedback_shift_generator, name='feedback_shift_generator'),
    path('create_feedback_shift_generator/', views.create_feedback_shift_generator, name='create_fsg'),

    path('matrix_shift_register/', views.matrix_shift_register, name='matrix_shift_register'),
    path('create_matrix_shift_register/', views.create_matrix_shift_register, name='create_msg'),

    path('2d_autocorr/', views.autocorr, name='autocorr'),
    path('create_2d_autocorr/', views.create_autocorr, name='create_autocorr'),
    path('create_2d_torus_autocorr/', views.create_torus_autocorr, name='create_torus_autocorr'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
import re

import numpy as np
import scipy.signal

from django.http import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from main.utils import get_polynomial, create_struct_matrix_var_1, get_states, generate_states, calc_t, factorize, \
    create_pvt_matrix, normalize_seq, generate_pvt_acf_image, generate_acf_image, create_struct_matrix_var_2, \
    create_S_matrix, create_sequence, calculate_hemming_weight, gcd, create_pvt_matrix_var_2, generate_torus, \
    generate_two_dim_acf_image, autocorrelation, polynomes_dict, generate_two_dim_acf_image_min, create_pvt_matrix1, \
    generate_matrix_acf_image


def feedback_shift_generator(request):
    return render(request, 'feedback_shift_generator.html', context={'polynomes': polynomes_dict})


def matrix_shift_register(request):
    return render(request, 'matrix_shift_register.html', context={'polynomes': polynomes_dict})


def autocorr(request):
    return render(request, '2d_autocorr.html', context={'polynomes': polynomes_dict})


def create_feedback_shift_generator(request):
    mode = request.GET.get('mode')
    seed_numbers = request.GET.getlist('seedNumbers[]', [])
    if mode == "2":
        polynom = request.GET.getlist('seedPolNumbers[]', [])
        polynom_coefficients = list(map(int, polynom))
    else:
        polynom = request.GET.get('valuesSelect')
        polynom_coefficients = get_polynomial(polynom)

    struct_matrix = create_struct_matrix_var_1(len(polynom_coefficients), polynom_coefficients)
    states = get_states(polynom_coefficients)
    seed_numbers = list(map(int, seed_numbers))
    state_matrix = [seed_numbers]

    results = {}

    while len(states):
        _, length, res = generate_states(states, state_matrix, polynom_coefficients)
        results[length] = res

    biggest_cycle = results[max(results.keys())]

    sequence = []
    for i in range(len(biggest_cycle)):
        sequence.append(biggest_cycle[i][1][0])

    hemming_weight = sum(1 for x in sequence if x == 1)
    t_exp_period = len(sequence)

    if mode == "2":
        t_period = t_exp_period

    else:
        j = 1
        match = re.search(r'<(\d+)', polynom)
        if match:
            j = int(match.group(1))

        t_period = calc_t(j, len(polynom_coefficients))

    f, seq_copy, n, m = factorize(sequence.copy())


    norm_sequence = normalize_seq(seq_copy)
    pvt_matrix = create_pvt_matrix_var_2(norm_sequence, n, m)


    acf_image_pvt = generate_pvt_acf_image(pvt_matrix, 0)
    image_base64 = generate_acf_image(sequence.copy())

    if not f:
        pvt_matrix_diagonal = create_pvt_matrix(norm_sequence, n, m)
        true_acf_image_pvt = generate_pvt_acf_image(np.array(pvt_matrix_diagonal), 1)
    else:
        true_acf_image_pvt = None



    result_container_html = render_to_string(
        'generate_fsg.html', {
            'sequence': sequence,
            'hemming_weight': hemming_weight,
            'struct_matrix': struct_matrix,
            'biggest_cycle': biggest_cycle,
            't_period': t_period,
            't_exp_period': t_exp_period,
            'acf_image': image_base64,
            'acf_image_pvt': acf_image_pvt,
            'true_acf_image_pvt': true_acf_image_pvt,
        }, request=request
    )
    response_data = {
        'message': 'Створено послідовність',
        'result_container_html': result_container_html,
    }

    return JsonResponse(response_data)


def create_matrix_shift_register(request):
    mode = request.GET.get('mode')
    if mode == "2":
        polynom_A = request.GET.getlist('seedPolAInputs[]', [])
        polynom_B = request.GET.getlist('seedPolBInputs[]', [])
        polynom_coefficients_A = list(map(int, polynom_A))
        polynom_coefficients_B = list(map(int, polynom_B))
    else:
        polynom_A = request.GET.get('valuesSelect_A')
        polynom_B = request.GET.get('valuesSelect_B')
        polynom_coefficients_A = get_polynomial(polynom_A)
        polynom_coefficients_B = get_polynomial(polynom_B)

    selected_rang = int(request.GET.get('selectedRang'))
    selected_i = int(request.GET.get('i'))
    selected_j = int(request.GET.get('j'))

    struct_matrix_A = create_struct_matrix_var_1(len(polynom_coefficients_A), polynom_coefficients_A)
    struct_matrix_B = create_struct_matrix_var_2(len(polynom_coefficients_B), polynom_coefficients_B)
    matrix_S = create_S_matrix(selected_rang, len(polynom_coefficients_A), len(polynom_coefficients_B))

    sequence, states = create_sequence(selected_i, selected_j, struct_matrix_A, struct_matrix_B, matrix_S)

    if mode == "2":
        t_period_A = 2 ** (len(polynom_coefficients_A)) - 1
        t_period_B = 2 ** (len(polynom_coefficients_B)) - 1
        t_period_C = len(sequence)

    else:
        j_1 = 1
        j_2 = 1
        match_A = re.search(r'<(\d+)', polynom_A)
        match_B = re.search(r'<(\d+)', polynom_B)
        if match_A:
            j_1 = int(match_A.group(1))
        if match_B:
            j_2 = int(match_B.group(1))

        t_period_A = int(calc_t(j_1, len(polynom_coefficients_A)) / gcd(calc_t(j_1, len(polynom_coefficients_A)), j_1))
        t_period_B = int(calc_t(j_2, len(polynom_coefficients_B)) / gcd(calc_t(j_2, len(polynom_coefficients_B)), j_2))
        t_period_C = int((t_period_A * t_period_B) / gcd(t_period_A, t_period_B))
    t_exp_period_C = len(sequence)

    hemming_weight = calculate_hemming_weight(selected_rang, len(polynom_coefficients_A), len(polynom_coefficients_B))
    hemming_exp_weight = sum(1 for x in sequence if x == 1)

    image_base64 = generate_matrix_acf_image(sequence.copy())

    result_container_html = render_to_string(
        'generate_msg.html', {
            'struct_matrix_A': struct_matrix_A,
            'struct_matrix_B': struct_matrix_B,
            'matrix_S': matrix_S,
            'sequence': sequence,
            'states': states,
            't_period_A': t_period_A,
            't_period_B': t_period_B,
            't_period_C': t_period_C,
            't_exp_period_C': t_exp_period_C,
            'hemming_weight': hemming_weight,
            'hemming_exp_weight': hemming_exp_weight,
            'acf_image': image_base64,
        }, request=request
    )
    response_data = {
        'message': 'Створено послідовність',
        'result_container_html': result_container_html,
    }

    return JsonResponse(response_data)


def create_autocorr(request):
    mode = request.GET.get('mode')
    if mode == "2":
        polynom_A = request.GET.getlist('seedPolAInputs[]', [])
        polynom_B = request.GET.getlist('seedPolBInputs[]', [])
        polynom_coefficients_A = list(map(int, polynom_A))
        polynom_coefficients_B = list(map(int, polynom_B))
    else:
        polynom_A = request.GET.get('valuesSelect_A')
        polynom_B = request.GET.get('valuesSelect_B')
        polynom_coefficients_A = get_polynomial(polynom_A)
        polynom_coefficients_B = get_polynomial(polynom_B)

    selected_rang = int(request.GET.get('selectedRang'))
    selected_i = int(request.GET.get('i'))
    selected_j = int(request.GET.get('j'))

    struct_matrix_A = create_struct_matrix_var_1(len(polynom_coefficients_A), polynom_coefficients_A)
    struct_matrix_B = create_struct_matrix_var_2(len(polynom_coefficients_B), polynom_coefficients_B)
    matrix_S = create_S_matrix(selected_rang, len(polynom_coefficients_A), len(polynom_coefficients_B))

    sequence, states = create_sequence(selected_i, selected_j, struct_matrix_A, struct_matrix_B, matrix_S)

    if mode == "2":
        t_period_A = 2 ** (len(polynom_coefficients_A)) - 1
        t_period_B = 2 ** (len(polynom_coefficients_B)) - 1
        t_period_C = len(sequence)

    else:
        j_1 = 1
        j_2 = 1
        match_A = re.search(r'<(\d+)', polynom_A)
        match_B = re.search(r'<(\d+)', polynom_B)
        if match_A:
            j_1 = int(match_A.group(1))
        if match_B:
            j_2 = int(match_B.group(1))

        t_period_A = int(calc_t(j_1, len(polynom_coefficients_A)) / gcd(calc_t(j_1, len(polynom_coefficients_A)), j_1))
        t_period_B = int(calc_t(j_2, len(polynom_coefficients_B)) / gcd(calc_t(j_2, len(polynom_coefficients_B)), j_2))
        t_period_C = int((t_period_A * t_period_B) / gcd(t_period_A, t_period_B))
    t_exp_period_C = len(sequence)

    hemming_weight = calculate_hemming_weight(selected_rang, len(polynom_coefficients_A), len(polynom_coefficients_B))
    hemming_exp_weight = sum(1 for x in sequence if x == 1)

    f, seq_copy, n, m = factorize(sequence.copy())
    norm_sequence = normalize_seq(seq_copy)

    pvt_matrix_var2 = create_pvt_matrix_var_2(norm_sequence, n, m)
    acf_image_pvt_var_2 = generate_pvt_acf_image(pvt_matrix_var2)

    if not f:
        pvt_matrix = create_pvt_matrix(norm_sequence, n, m)
        acf_image_pvt = generate_pvt_acf_image(pvt_matrix)
    else:
        acf_image_pvt = acf_image_pvt_var_2

    result_container_html = render_to_string(
        'generate_2d_autocorr.html', {
            'struct_matrix_A': struct_matrix_A,
            'struct_matrix_B': struct_matrix_B,
            'matrix_S': matrix_S,
            'sequence': sequence,
            'states': states,
            't_period_A': t_period_A,
            't_period_B': t_period_B,
            't_period_C': t_period_C,
            't_exp_period_C': t_exp_period_C,
            'hemming_weight': hemming_weight,
            'hemming_exp_weight': hemming_exp_weight,
            'acf_image_pvt': acf_image_pvt,
            'acf_image_pvt_var_2': acf_image_pvt_var_2,
        }, request=request
    )
    response_data = {
        'message': 'Створено послідовність',
        'result_container_html': result_container_html,
    }

    return JsonResponse(response_data)


def create_torus_autocorr(request):
    mode = request.GET.get('mode')
    if mode == "2":
        polynom_A = request.GET.getlist('seedPolAInputs[]', [])

templates/2d_autocorr.html
{% extends 'main.html' %}

{% block content %}
    <div class="container my-3">
        <div class="row">
            <div class="col-md-5">
                <div class="d-flex flex-row mb-3">
                    <input type="radio" id="mode_static" name="mode" value="static" checked>
                    <label for="mode_static"> Обрати незвідний поліном</label>
                </div>
                <label for="keys_A">Оберіть ступінь матриці А:</label>
                <select id="keys_A" onchange="updateValues_A()" class="form-select my-2">
                    <option value="" selected disabled hidden>Оберіть ступінь</option>
                    {% for key in polynomes %}
                        <option value="{{ key }}">{{ key }}</option>
                    {% endfor %}
                </select>
                <div id="pol_container_A" style="display: none">
                    <label id="labelPol_A">Введіть поліном A:</label>
                    <div class="input-group" id="inputPolContainer_A">
                        <span class="input-group-text">Введіть поліном A</span>
                    </div>

                    <label id="values_A_label">Оберіть поліном:</label>
                    <select id="values_A" class="form-select my-2">
                        <option value="" selected disabled hidden>Оберіть поліном A</option>
                    </select>
                </div>
            </div>

            <div class="col-md-5">
                <div class="d-flex flex-row mb-3">
                    <input type="radio" id="mode_dynamic" name="mode" value="dynamic">
                    <label for="mode_dynamic">Ввести поліном</label>
                </div>
                <label for="keys_B">Оберіть ступінь матриці B:</label>
                <select id="keys_B" onchange="updateValues_B()" class="form-select my-2">
                    <option value="" selected disabled hidden>Оберіть ступінь</option>
                    {% for key in polynomes %}
                        <option value="{{ key }}">{{ key }}</option>
                    {% endfor %}
                </select>
                <div id="pol_container_B" style="display: none">
                    <label id="labelPol_B">Введіть поліном B:</label>
                    <div class="input-group" id="inputPolContainer_B">
                        <span class="input-group-text">Введіть поліном B</span>
                    </div>

                    <label id="values_B_label">Оберіть поліном:</label>
                    <select id="values_B" class="form-select my-2">
                        <option value="" selected disabled hidden>Оберіть поліном B</option>
                    </select>
                </div>
            </div>

            <div class="col-md-2 d-flex flex-column justify-content-end pb-2">
                <label for="rang" id='rang_label' style="display:none;">Оберіть ранг:</label>

                <select id="rang" class="form-select my-2" style="display:none;">
                    <option value="" selected disabled hidden>Оберіть ранг</option>
                </select>

                <div class="input-group" id="input-group_i_j" style="display: none;">
                    <span class="input-group-text">Введіть i, j:</span>
                    <input id="i" type="text" placeholder="1" value=1 class="form-control">
                    <input id="j" type="text" placeholder="1" value=1 class="form-control">
                </div>

            </div>

            <div class="col-md-12 d-flex justify-content-center">
                <button onclick="generate_msg()" id="generateButton" style="display:none;"
                        class="btn btn-outline-primary w-100 my-2">Створити
                </button>
            </div>

        </div>
        <div class="container result_container my-3 bg-info bg-opacity-10"></div>
        
    </div>



    <script>
        function updateValues_A() {

            var selectedKey = document.getElementById("keys_A").value;
            var labelPol_A = document.getElementById('labelPol_A');
            var label_values_A = document.getElementById('values_A_label');
            var valuesSelect = document.getElementById("values_A");
            var inputPolContainer_A = document.getElementById("inputPolContainer_A");
            if (staticModeRadio.checked) {


                inputPolContainer_A.innerHTML = '';
                labelPol_A.style.display = 'none';
                valuesSelect.style.display = 'flex';
                label_values_A.style.display = 'flex';

                valuesSelect.innerHTML = '';

                var values = {{ polynomes|safe }}[selectedKey];
                if (values) {
                    for (var i = 0; i < values.length; i++) {
                        var option = document.createElement("option");
                        option.text = values[i];
                        valuesSelect.add(option);
                    }
                }
            }
            if (dynamicModeRadio.checked) {

                labelPol_A.style.display = 'flex';
                valuesSelect.style.display = 'none';
                label_values_A.style.display = 'none';

                inputPolContainer_A.innerHTML = '';
                for (var j = 0; j < selectedKey; j++) {
                    var input_pol = document.createElement("input");
                    input_pol.type = "text";
                    input_pol.name = "input_" + j;
                    input_pol.className = "form-control my-2 pol_A_seed";
                    input_pol.placeholder = "0";
                    input_pol.value = 1;
                    input_pol.maxLength = 1;
                    inputPolContainer_A.appendChild(input_pol);
                }
            }
        }

        function updateValues_B() {

            var selectedKey = document.getElementById("keys_B").value;
            var labelPol_B = document.getElementById('labelPol_B');
            var valuesSelect = document.getElementById("values_B");
            var inputPolContainer_B = document.getElementById("inputPolContainer_B");
            var label_values_B = document.getElementById('values_B_label');

            if (staticModeRadio.checked) {

                inputPolContainer_B.innerHTML = '';
                labelPol_B.style.display = 'none';
                valuesSelect.style.display = 'flex';
                label_values_B.style.display = 'flex';

                valuesSelect.innerHTML = '';
                var values = {{ polynomes|safe }}[selectedKey];
                if (values) {
                    for (var i = 0; i < values.length; i++) {
                        var option = document.createElement("option");
                        option.text = values[i];
                        valuesSelect.add(option);
                    }
                }
            }
            if (dynamicModeRadio.checked) {

                labelPol_B.style.display = 'flex';
                valuesSelect.style.display = 'none';
                label_values_B.style.display = 'none';

                inputPolContainer_B.innerHTML = '';
                for (var j = 0; j < selectedKey; j++) {
                    var input_pol = document.createElement("input");
                    input_pol.type = "text";
                    input_pol.name = "input_" + j;
                    input_pol.className = "form-control my-2 pol_B_seed";
                    input_pol.placeholder = "0";
                    input_pol.value = 1;
                    input_pol.maxLength = 1;
                    inputPolContainer_B.appendChild(input_pol);
                }
            }


            var generateButton = document.getElementById("generateButton");
            generateButton.style.display = "block";
            select_rang();
        }

        var staticModeRadio = document.getElementById('mode_static');
        var dynamicModeRadio = document.getElementById('mode_dynamic');

        staticModeRadio.addEventListener('change', function () {
            if (staticModeRadio.checked) {
                updateValues_A();
                updateValues_B();
            }
        });

        dynamicModeRadio.addEventListener('change', function () {
            if (dynamicModeRadio.checked) {
                updateValues_A();
                updateValues_B();
            }
        });


        function generate_msg() {
            var mode = 0;


            var selectedRang = parseInt(document.getElementById("rang").value);
            var i = document.getElementById("i").value;
            var j = document.getElementById("j").value;
            var seedPolANumbers = [];
            var seedPolBNumbers = [];

            if (staticModeRadio.checked) {
                mode = 1;
                var valuesSelect_A = document.getElementById("values_A").value;
                var valuesSelect_B = document.getElementById("values_B").value;
            }

            if (dynamicModeRadio.checked) {
                mode = 2;
                var seedPolAInputs = document.querySelectorAll(".pol_A_seed");
                var seedPolBInputs = document.querySelectorAll(".pol_B_seed");


                seedPolAInputs.forEach(function (input) {
                    var polA_value = parseInt(input.value);
                    if (!isNaN(polA_value)) {
                        seedPolANumbers.push(polA_value);
                    }
                });
                seedPolBInputs.forEach(function (input) {
                    var polB_value = parseInt(input.value);
                    if (!isNaN(polB_value)) {
                        seedPolBNumbers.push(polB_value);
                    }
                });
            }


            // делаем post запрос через ajax не перезагружая страницу
            $.ajax({
                type: "GET",
                url: '{% url 'main:create_autocorr' %}',
                data: {
                    mode: mode,
                    seedPolAInputs: seedPolANumbers,
                    seedPolBInputs: seedPolBNumbers,
                    valuesSelect_A: valuesSelect_A,
                    valuesSelect_B: valuesSelect_B,
                    selectedRang: selectedRang,
                    i:i,
                    j:j,

                },
                success: function (data) {
                    var result_container = $(".result_container");
                    result_container.html(data.result_container_html);
                },

                error: function (data) {
                    console.log(data);
                },
            });

        }

        function select_rang() {
            var rangSelect = document.getElementById("rang");
            var rang_label = document.getElementById("rang_label");
            rangSelect.style.display = "block";
            rang_label.style.display = "block";


            var selectedKey = document.getElementById("keys_A").value;

            rangSelect.innerHTML = '';

            for (var i = 1; i <= selectedKey; i++) {
                var option = document.createElement("option");
                option.text = i;
                option.value = i;
                rangSelect.appendChild(option);
            }
        }

        function select_i_j() {
            var input_group = document.getElementById("input-group_i_j");
            input_group.style.display = "flex";
        }

        var keys_A = document.getElementById("keys_A");
        var keys_B = document.getElementById("keys_B");

        keys_A.addEventListener("change", function () {
            var pol_container_A = document.getElementById('pol_container_A');
            pol_container_A.style.display = 'block';
            console.log(1);
            select_rang();
            select_i_j();
        });

        keys_B.addEventListener("change", function () {
            var pol_container_B = document.getElementById('pol_container_B');
            pol_container_B.style.display = 'block';
        });


    </script>
{% endblock %}

templates/generate_2d_autocorr_torus.html
<span class="text-center">
    <h4>Періодична АКФ Тору станів</h4>
    <img src="data:image/png;base64,{{ acf_image_torus|safe }}" alt="Plot" class="acf-image">
</span>

<span class="text-center">
    <h4>Аперіодична АКФ Тору станів</h4>
    <img src="data:image/png;base64,{{ acf_image_torus_a|safe }}" alt="Plot" class="acf-image">
</span>
<span class="text-center">
    <h4>Аперіодична АКФ min Тору станів</h4>
    <img src="data:image/png;base64,{{ acf_image_torus_min|safe }}" alt="Plot" class="acf-image">
</span>

templates/generate_fsg.html
<div class="row">
    <div class="col-md-6">
        <h4>Структурна матриця:</h4>

        <table class="table table-bordered border-info">
            {% for row in struct_matrix %}
                <tr>
                    {% for el in row %}
                        <td>{{ el }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
        <div class="scroll-container-seq">
            <h4>Послідовність:</h4>
            <p class="fw-bold">
                {% for el in sequence %}
                    {{ el }}
                {% endfor %}
            </p>
        </div>
        <h4>Вага Хеммінгу: </h4>
        <p class="fw-bold">{{ hemming_weight }}</p>

        <h4>T: </h4>
        <p class="fw-bold">{{ t_period }}</p>

        <h4>T(experimental): </h4>
        <p class="fw-bold">{{ t_exp_period }}</p>

        <h4>Стани послідовності:</h4>
        <div class="scroll-container">
            <table class="table table-striped table-hover text-center">
                <thead>
                <tr>
                    <th scope="col">N</th>
                    <th scope="col">Стан</th>
                    <th scope="col">N₁₀</th>
                </tr>
                </thead>
                {% for row in biggest_cycle %}
                    <tr>
                        {% for el in row %}
                            <td>{{ el }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>


    <div class="col-md-6">
        <h4>АКФ послідовності</h4>
        <img src="data:image/png;base64,{{ acf_image|safe }}" alt="Plot">
        <h4>2Д АКФ</h4>
        <img src="data:image/png;base64,{{ acf_image_pvt|safe }}" alt="Plot">
        {% if true_acf_image_pvt %}
            <h4>MacWilliams АКФ</h4>
            <img src="data:image/png;base64,{{ true_acf_image_pvt|safe }}" alt="Plot">
        {% endif %}


    </div>

</div>

templates/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>КР ХОМА ЗМІЄВСЬКА</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
    <link href="{% static 'styles.css' %}" rel="stylesheet"/>
</head>
<body>

{% block nav %}
<div class="container">
    <nav class="navbar bg-light">
      <div class="container-fluid">
        <a class="a-nav navbar-brand" href="{% url 'main:feedback_shift_generator' %}">Генератор ЗРЗЗ</a>
        <a class="a-nav navbar-brand" href="{% url 'main:matrix_shift_register' %}">Генератор MЗP</a>
        <a class="a-nav navbar-brand" href="{% url 'main:autocorr' %}">2D АКФ</a>
      </div>
    </nav>
</div>
{% endblock %}

    
<main>
{% block content %}
{% endblock %}

{% block result %}
{% endblock %}
</main>

{% block footer %}
    <footer>
    <ul class="nav justify-content-center border-bottom mt-1">
        <p class="text-center text-muted">Курсова робота з АПА студентів групи КН-321В</p>
    </ul>
    <p class="text-center text-muted">Виконали: Хома Д.М. та Змієвська І.В.</p>
  </footer>
{% endblock %}

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>


<script src="{% static 'scripts.js' %}"></script>
</body>
</html>